name: Java CI with Gradle on macOS

on:
  push:
    branches: ["main"]

jobs:
  test-safari:
    env:
      BROWSER: safari

    runs-on: macOS-11.0

    steps:
    - uses: actions/checkout@v3
    - name: Install Xcode
      run: sudo softwareupdate --install Xcode
    - name: Install XQuartz
      run: brew install xquartz --cask
    - name: Make gradlew script executable
      run: chmod +x gradlew
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'corretto'
    - name: Build with Gradle
      run: ./gradlew test -Dbrowser=$BROWSER




    
        
